[package]
name = "carto"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
digest = "0.10"
directories = "4.0"
dirs = "4.0"
hex = "0.4"
html5ever = "0.25"
log = "0.4"
regex = "1"
reqwest = "0.11"
scraper = "0.12"
sha2 = "0.10"
simple_logger = "1.16"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite", "chrono"] }
tokio = { version = "1", features = ["full"] }
url = "2.2"