[package]
name = "cartographer"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[dependencies]
dirs = "4.0.0"
directories = "4.0.1"
rusqlite = "0.26.1"
reqwest = "0.11.6"