[package]
name = "carto"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
digest = "0.10"
directories = "4.0"
dirs = "4.0"
ego-tree = "0.6.2"
hex = "0.4"
html5ever = "0.25"
log = "0.4"
regex = "1"
reqwest = "0.11"
rocket = { version = "0.5.0-rc.1", features = [ "json" ] }
serde = "1.0"
sha2 = "0.10"
simple_logger = "2.1"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite", "chrono"] }
tantivy = "0.16"
tendril = "0.4.2"
tokio = { version = "1", features = ["full"] }
url = "2.2"