[package]
name = "carto-cli"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[workspace]
members = [
    "carto",
    "carto-indexer"
]

[[bin]]
name = "cli"
path = "src/main.rs"

[[bin]]
name = "indexer"
path = "carto-indexer/src/main.rs"

[[bin]]
name = "searcher"
path = "carto-searcher/src/main.rs"

[dependencies]
carto = { path = "./carto" }
directories = "4.0.1"
dirs = "4.0.0"
log = "0.4.14"
rusqlite = "0.26.1"
sea-orm = { version = "^0", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false }
tokio = { version = "1", features = ["full"] }
simple_logger = "1.16.0"
url = "2.2.2"