[package]
name = "carto-cli"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]

[dependencies]
chrono = "0.4"
digest = "0.10"
directories = "4.0"
dirs = "4.0"
hex = "0.4"
log = "0.4"
regex = "1"
reqwest = "0.11"
rusqlite = { version = "0.26", features = ["chrono"] }
sha2 = "0.10"
simple_logger = "1.16"
tokio = { version = "1", features = ["full"] }
url = "2.2"